{{- $fullName := include "ziplinee-ci-web.fullname" . -}}
{{- $labels := include "ziplinee-ci-web.labels" . -}}
{{- range $.Values.extraConfigmaps -}}
kind: ConfigMap
apiVersion: v1
metadata:
  name: {{ $fullName }}.{{ .key }}
  labels:
    {{- $labels | nindent 4 }}
  {{- with .annotations }}
  annotations:
    {{- toYaml . | nindent 4 -}}
  {{- end }}
{{- with .data }}
data:
  {{- tpl . $ | nindent 2 }}
{{- end }}
---
{{- end }}