{{- if $.Values.iap.enabled }}
kind: Secret
apiVersion: v1
metadata:
  name: {{ template "ziplinee-ci-web.fullname" . }}.backendconfig
  namespace: {{ .Release.Namespace | quote }}
  labels:
    helm.sh/chart: {{ template "ziplinee-ci-web.chart" . }}
    app.kubernetes.io/name: {{ template "ziplinee-ci-web.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name | quote }}
    app.kubernetes.io/managed-by: {{ .Release.Service | quote }}
  {{- with $.Values.labels }}
    {{- toYaml . | nindent 4 }}
  {{- end }}
type: Opaque
data:
  client_id: {{ $.Values.iap.clientId | b64enc }}
  client_secret: {{ $.Values.iap.clientSecret | b64enc }}
{{- end }}