{{- if $.Values.iap.enabled }}
{{- if $.Capabilities.APIVersions.Has "cloud.google.com/v1/BackendConfig" -}}
apiVersion: cloud.google.com/v1
{{- else -}}
apiVersion: cloud.google.com/v1beta1
{{- end }}
kind: BackendConfig
metadata:
  name: {{ template "ziplinee-ci-api.fullname" . }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    helm.sh/chart: {{ template "ziplinee-ci-api.chart" . }}
    app.kubernetes.io/name: {{ template "ziplinee-ci-api.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name | quote }}
    app.kubernetes.io/managed-by: {{ .Release.Service | quote }}
  {{- with $.Values.labels }}
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  iap:
    enabled: true
    oauthclientCredentials:
      secretName: {{ template "ziplinee-ci-api.fullname" . }}.backendconfig
  timeoutSec: 120
{{- end }}