{{- if and $.Values.tls.enabled $.Values.tls.certManager.enabled }}
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ include "ziplinee-ci-api.fullname" . }}
spec:
  secretName: {{ include "ziplinee-ci-api.fullname" . }}.tls
  chainOutputFormat: Combined
  issuerRef:
    name: {{ $.Values.tls.certManager.issuer }}
    kind: ClusterIssuer
  dnsNames:
    - {{ $.Values.baseHost }}
    - {{ $.Values.integrationsHost }}
{{- end }}
