{{- if $.Values.serviceAccount.create }}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "ziplinee-ci-api.fullname" . }}.builder
  namespace: {{ include "ziplinee-ci-api.jobNamespace" . }}
  labels:
    {{- include "ziplinee-ci-api.labels" . | nindent 4 }}
rules:
- apiGroups:
  - ""
  resources:
  - pods
  - pods/log
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
- apiGroups:
  - ""
  resources:
  - configmaps
  - secrets
  verbs:
  - get
  - list
  - create
  - delete
{{- end }}