apiVersion: v1
kind: Service
metadata:
  name: {{ include "ziplinee-ci-api.fullname" . }}
  labels:
    {{- include "ziplinee-ci-api.labels" . | nindent 4 }}
  {{- if or $.Values.service.annotations $.Values.iap.enabled }}
  annotations:
  {{- with $.Values.service.annotations }}
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- if $.Values.iap.enabled }}
    beta.cloud.google.com/backend-config: '{"default": "{{ template "ziplinee-ci-api.fullname" . }}"}'
  {{- end }}
  {{- end }}
spec:
  {{- if $.Values.iap.enabled }}
  type: NodePort
  {{- else }}
  type: {{ $.Values.service.type }}
  {{- end }}
  ports:
    - port: {{ $.Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "ziplinee-ci-api.selectorLabels" . | nindent 4 }}
