{{- if $.Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "ziplinee-ci-api.serviceAccountName" . }}
  labels:
    {{- include "ziplinee-ci-api.labels" . | nindent 4 }}
  {{- with $.Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
